<a href="https://colab.research.google.com/github/andrearidi/Hult/blob/main/DataCorrection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
#read excel file
df = pd.read_excel("/content/rollingsales_bronx.xlsx") #preview data
df.head()

,Bronx Rolling Sales. All Sales From January 2023 - December 2023,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,PTS Sales Data as of 1/9/2024,Unnamed: 20
0,"For sales prior to the Final Roll, Neighborhoo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Building Class Category is based on Building C...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Note: Condominium and cooperative sales are on...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASEMENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
4,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3030,66,NaN,A1,4453 PARK AVENUE,NaN,...,1,0,1,1646,1497,1899,1,A1,215000,2023-04-18 00:00:00

In [4]:
#we read the data in again but skill 3 rows this time
df = pd.read_excel("/content/rollingsales_bronx.xlsx", skiprows = 4, header = [0])
df

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASEMENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3030,66,NaN,A1,4453 PARK AVENUE,NaN,...,1.0,0.0,1.0,1646.0,1497.0,1899.0,1,A1,215000,2023-04-18
1,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3030,66,NaN,A1,4453 PARK AVENUE,NaN,...,1.0,0.0,1.0,1646.0,1497.0,1899.0,1,A1,570000,2023-08-23
2,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3035,52,NaN,A1,461 EAST 178 STREET,NaN,...,1.0,0.0,1.0,1782.0,1548.0,1899.0,1,A1,0,2023-04-14
3,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3053,86,NaN,S0,2364 WASHINGTON AVENUE,NaN,...,1.0,2.0,3.0,1911.0,4080.0,1931.0,1,S0,0,2023-10-24
4,2,BATHGATE,02 TWO FAMILY DWELLINGS,1,2904,22,NaN,B9,454 EAST 172 STREET,NaN,...,2.0,0.0,2.0,1658.0,1428.0,1901.0,1,B9,350000,2023-06-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5601,2,WOODLAWN,10 COOPS - ELEVATOR APARTMENTS,2,3398,97,NaN,D4,"4295 WEBSTER AVENUE, 4K",NaN,...,NaN,NaN,NaN,NaN,NaN,1957.0,2,D4,114500,2023-03-01
5602,2,WOODLAWN,10 COOPS - ELEVATOR APARTMENTS,2,3398,97,NaN,D4,"4295 WEBSTER AVENUE, 5C",NaN,...,NaN,NaN,NaN,NaN,NaN,1957.0,2,D4,135000,2023-10-16
5603,2,WOODLAWN,10 COOPS - ELEVATOR APARTMENTS,2,3398,97,NaN,D4,"4295 WEBSTER AVENUE, 5F",NaN,...,NaN,NaN,NaN,NaN,NaN,1957.0,2,D4,265000,2023-09-07
5604,2,WOODLAWN,22 STORE BUILDINGS,4,3380,46,NaN,K1,4361 KATONAH AVENUE,NaN,...,0.0,1.0,1.0,9699.0,3400.0,1970.0,4,K1,0,2023-04-17
5605,2,WOODLAWN,35 INDOOR PUBLIC AND CULTURAL FACILITIES,4,3380,54,NaN,P8,4351 KATONAH AVENUE,NaN,...,0.0,1.0,1.0,3121.0,2520.0,1970.0,4,P8,0,2023-04-17